### ISSUE TITLE
3.0 tracking issue - rewriting source generation

### ISSUE THREAD

**Issue by martinothamar** [martinothamar/Mediator#98]
Things I want to solve/merge in 3.0. 

To solve these I'll be rewriting be rewriting the source generation process. I will be starting out in an experiment branch
and seek feedback before bringing it into main (which will be the 3.0 preview).
Sorted from most difficult to least difficult (assumed).

- [ ] Improve performance for large number of messages (#48)
- [ ] Improvements for large solutions (#97)
- [ ] Support generic messages (#76)
- [ ] Fix unfortunate naming conflict between namespace and concrete Mediator type (#65)
- [ ] Support .NET Standard 2.0 (#53)
- [ ] Improve diagnostics (#49)
- [ ] Reorder cancellation token parameters for functions, to realign with MediatR (#52)
- [ ] Remove uneccessary dep on System.Threading.Tasks.Extensions (#86)

**Comment by martinothamar** [comment]
Another thing I've considered: should this library be renamed? "Mediator" is kind of plain/vanilla. It's basically a working title that I never changed. Feel free to drop suggestions and feedback..

**Comment by TimothyMakkison** [comment]
> Improve performance for large number of messages #440

Have you looked at using liquid instead of scriban? [Fluid](https://github.com/sebastienros/fluid) appears to be more [performant](https://github.com/sebastienros/fluid) than scriban. Not sure if liquid supports all your requirements

**Comment by martinothamar** [comment]
Not considered it yet, but open to it! Would be fairly easy to migrate I think. I'd like to hold off on that until the top 4 issues are completed though, since there will be significant changes in the source generator

**Comment by TimothyMakkison** [comment]
I'm not sure how much scriban affects performance tbh. Perhaps parsing the template once and reusing it could help, although I'm not sure if source generators allow this.

> I'd like to hold off on that until the top 4 issues are completed though, since there will be significant changes in the source generator

Looking forward to seeing your changes, your project has been super when improving Mapperly.

**Comment by ejsmith** [comment]
This project looks awesome! I'm interested in a conventional handler approach either on top of this library or as an additional source generator. Something that decouples the handlers from the messaging library like this: https://wolverine.netlify.app/guide/handlers/  It would just discover handlers by convention and generate the concrete handler that implements your `IRequestHandler` and friends interfaces. Any interest in this?

**Comment by martinothamar** [comment]
So that would only affect handlers right? The requests/notifications would still use the appropriate interface?

Related: one thing I like a lot about Wolverine (and Marten) is that there is support for static functions as handlers. The typical case for request/notification handlers is that they are stateless, so it feels silly allocating an object simply to invoke a method. There are often injected services, but they can be injected as parameters to the function as well.. Seeing as this is a performance oriented library, that's something I would like to explore in the future. ASP.NET Core minimal APIs is kind of also going in that direction, having static functions as handlers, and we can now have static abstract methods in interfaces.. Might be something there.

So yes there is some interest there from my side for sure (taking inspiration from the Wolverine approach in general), but I'm not sure how it could be integrated into this library. I'll think some more about this while refactoring the source generator.

Btw, a challenge with source generators is that they don't compose at all, so I don't think this is solvable as an additional source generator (the Mediator source generator wouldn't have access to code generated by another source generator)

**Comment by ejsmith** [comment]
Yes, this would only affect the handlers and not sending the messages.

Yeah, it really sucks that source generators can't simply be ordered by a priority with same priority using the same compilation model, but any subsequent ones would get an updated compilation model and be able to inspect code from previous priorities.

**Comment by ejsmith** [comment]
Was just looking at https://github.com/dotnet/runtime/pull/86121 and thinking how doing something similar would make an amazing mediator implementation.

**Comment by martinothamar** [comment]
Yea it's on our radar for sure. @Tornhoof also brought it up here: https://github.com/martinothamar/Mediator/issues/7#issuecomment-1603053555

Since they are bringing it into ASP.NET Core atm I'm assuming the interceptors proposal is basically approved for .NET 8/C# 12? 😄 
I am very tempted to go all in on .NET 8 SDK requirement and using interceptors. I haven't been able to come up with a design for 3.0 that solves all the issues in the OP (while keeping the perf that is), but with interceptors everything becomes a lot simpler

**Comment by ejsmith** [comment]
Yeah, interceptors was merged into main.

**Comment by TimothyMakkison** [comment]
It might be better to wait for these changes but will you be adding support for incremental pipeline caching? The output from `CompilationAnalyzer` could be turned into an `Equatable` friendly type. 

I'd be willing to have a go at this.

**Comment by KennethHoff** [comment]
> Since they are bringing it into ASP.NET Core atm I'm assuming the interceptors proposal is basically approved for .NET 8/C# 12? 😄

Most likely, but one thing I've realized about the dotnet codebases is that they'll update everything the moment it's available to be done. It's really quite interesting. They rewrote practically every instance they did null checks for parameters with the `!!` proposal a few years back before that was reverted. Same with `ArgumentNullException.ThrowIfNull(param)`, and they've said they will with primary Constructors whenever that spec gets finalized.


So while it most likely will pass, I wouldn't go all-in just yet, especially since they've repeatedly said that it is a preview feature that likely will get changed or maybe even removed  (although I highly doubt the latter due to just how important it is for the AoT story they're going all-in on)

**Comment by ejsmith** [comment]
They are somewhat committed to it because of the AOT story and they are going to be using it a lot (already has multiple PRs accepted) to generate code that supports that. They would need to rewrite a lot of their code as well. Not to mention that this will be a pretty straight forward thing to replace if they come up with a different similar approach.

**Comment by TimothyMakkison** [comment]
> I am very tempted to go all in on .NET 8 SDK requirement and using interceptors.

> https://github.com/martinothamar/Mediator/issues/7#issuecomment-1609007408

Correct me if I'm wrong, but it's already possible to create a pseudo interceptor in all versions of .NET. By using the [caller line number](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerlinenumberattribute?view=net-7.0) and [caller file path](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callerfilepathattribute?view=net-7.0), it is possible to differentiate each caller and respond appropiately,

```C#
public static TResponse Send<TRequest, TResponse>(.... parameters go here, [CallerLineNumber] line = 0, [CallerFilePath] file = "")
...

public static void AddMediator(.... parameters go here, [CallerLineNumber] line = 0, [CallerFilePath] file = "")
{
    // an efficient condition can be built using the line number, file path length and varying chars in the file path
    // not sure how much the compiler will do
    return (line, path) switch
    {
        (0, _) => Mediator1.AddMediator(services),
        (42, { Length: 15 }) => Mediator2.AddMediator(services),
        (42, { Length: 21 }) => Mediator2.AddMediator(services),
        _ => throw new ArgumentOutOfRangeException()
    }
}
```
Note that this may not work if the same method is called repeatedly on the same line. This is very unlikely to occur for `Send` or `AddMediator`, however a check and diagnostic could be used to prevent this.

**Comment by dev-anton-ko** [comment]
Speaking about "Support generic messages".
Is this including support of generic Queries/Requests/Commands?

**Comment by martinothamar** [comment]
Yes, thats not possible currently, and requires rewriting the source generation of the `IMediator` implementation

**Comment by KANekT** [comment]
@martinothamar Project is frozen or is there a plan and date for the new version ?

**Comment by KANekT** [comment]
ok, Thanks. I'm currently using version 3 in my project. Therefore, I am interested in the further fate of the package.

**Comment by JohnGalt1717** [comment]
My personal request is for integrations with Redis/RabbitMQ/Kafka etc. to incrementally take this into doing distributed requests and requests/responses.

I'd love to have a library that does mediator first and then transparently goes up the chain to distributed requests automatically.

**Comment by KANekT** [comment]
> My personal request is for integrations with Redis/RabbitMQ/Kafka etc. to incrementally take this into doing distributed requests and requests/responses.
> 
> I'd love to have a library that does mediator first and then transparently goes up the chain to distributed requests automatically.

I think you need to do this in your code yourself. If it is possible to make an example for this package

**Comment by aradalvand** [comment]
+1 for the interceptor approach. It very much seems like the perfection of mediator performance.

**Comment by R4ND3LL** [comment]
> Allow handlers to be internal - i.e. messages are public contracts, handlers are hidden

Is this feature implemented in the preview yet?   If so, how can it be done?

Without using internals visible to, it would make sense to have a source generated mediator within each library containing internal handlers, that way there is no visibility issue, however the root IMediator would still have to coordinate the execution.

**Comment by Foxtrek64** [comment]
> Another thing I've considered: should this library be renamed? "Mediator" is kind of plain/vanilla. It's basically a working title that I never changed. Feel free to drop suggestions and feedback..

Martiator 👍

**Comment by portal7** [comment]
Searching for implementation tips as a developer can be challenging without relying on Google. Two common issues often arise:

Searches for design patterns frequently lead to MediatR, even when you're looking for general information about the mediator pattern.

Search engines prioritize MediatR results, assuming you need details about using a mediator in C#, which circles back to MediatR.

This makes it easy to fall into **a MediatR loop unintentionally.**

Renaming the package to a more distinct name would be ideal to avoid this confusion.

**Comment by Foxtrek64** [comment]
Jokes aside, I agree with @portal7. I too often find a lot of search results end up suggesting things regarding MediatR. DuckDuckGo tends to be a little bit better, but then a lot of articles talking about the mediator pattern end up using MediatR so we're right back there.

I am awful at naming things, but here's a few ideas I came up with:

- FastMediator (self-descriptive, and destinct from MediatR)
- M# or MediatorSharp (a bit cliche perhaps)
- Sprinter (comes from the idea of C# liking to rename types, like Futures being Tasks. I imagine the mediator pattern might be called the "Relay" pattern, because we are relaying information via commands or requests to cause something to happen. A sprinter runs a relay, and this library is also intended to run the relay service, though "run" here is being used in two different senses.)

**Comment by codymullins** [comment]
I see it's been a bit since updates for 3.0 preview (no judgment). Any news on how stable or not stable it is to use vs. using 2.x?

**Comment by gfoidl** [comment]
> how stable

In one (quite big) project I use it in production w/o any problems. So I'd say it's stable (didn't encounter any errors neither during build nor at runtime).

Update from 2.x -> 3 was easy, just changes in the method-signature because of CancellationToken moved last (as recommended) in the behaviors.

**Comment by martinothamar** [comment]
Since 3.0 has taken so much time, there's a good chance #48 will be the last piece of work going into it. And last I worked on that it's not a perfect design (IMO that is still interceptors), but had good results last I checked. 4.0 will probably/hopefully be based on interceptors and some bigger changes. Are interceptors still preview or were they stabilized as part of 9?

**Comment by neozhu** [comment]
Thanks so much for the effort you've put into this! I'm currently using preview 27  on dotnet 9 and haven't encountered any issues so far. Everything works great on my end. Looking forward to seeing the release new version soon!

**Comment by gfoidl** [comment]
> Are interceptors still preview or were they stabilized as part of 9?

It's something halfway in between...

ASP.NET Core uses interceptors in production, so I'd say they're ready to use (with .NET 9).

**Comment by codymullins** [comment]
Thanks for the feedback. I've been using the preview version in the app we're planning to launch shortly and it seems to be functioning well.

**Comment by ejsmith** [comment]
I'm confused on trying to figure out if this project is dead or not. :-)

**Comment by KANekT** [comment]
I also don't understand the status of the project - no updates for 6 months...

I found alternative https://immediateplatform.dev/

**Comment by ziongh** [comment]
We could use something like [Pure.DI](https://github.com/DevTeam/Pure.DI), so we can do a complete source generation solution for the injection of the handlers.

**Comment by martinothamar** [comment]
Some progress on the "large project performance"-story (and perf in general really): https://github.com/martinothamar/Mediator/issues/48#issuecomment-2817213047 and #176 

Seeing as I've been delayed for a very long time, I'm tempted to go for a v3 stable release with that PR (and potentially some small follow up ones). I could for example go to beta or RC first, let it sit for a little while and test it out myself, and then go stable within some weeks?

**Comment by ejsmith** [comment]
I say go for it. :-)

**Comment by martinothamar** [comment]
I finally merged https://github.com/martinothamar/Mediator/pull/176, which is the largest piece of the v3 puzzle. Now I just want to triage the issue tracker first and do some more testing on some real world projects as well. In the meantime I've updated the README with some new benchmarks and stuff and now recommend using the latest v3 prereleases as opposed to v2.1. Any help in testing is greatly appreciated

**Comment by goremykin** [comment]
@martinothamar,  I am not sure that this is the right place to ask such questions, but anyway. Could you explain why Singleton and ValueTask were chosen by default?
As far as I understand, in most cases (web development), handlers contain calls to a database or third-party services.

If there any discussion so I can read the points?

**Comment by goremykin** [comment]
@martinothamar, Thanks for the answer. But what do you think about singleton by default? It's difficult to imagine the app where all things you inject into handlers are singleton friendly (like ef, http clients, etc).

**Comment by martinothamar** [comment]
Ok now there is a discussion: https://github.com/martinothamar/Mediator/discussions/210
I tried to answer and give my opinions and background there 😄 Feel free to chime in

**Comment by dsadlik-krk** [comment]
Is there any news on the release date for version 3?

**Comment by ejsmith** [comment]
Hey everyone! Given the lack of response here, I decided to start a new project with ideas I've had about what my ideal mediator library would look like.

I've been working on **[Foundatio.Mediator](https://github.com/FoundatioFx/Foundatio.Mediator)** - a blazingly fast, convention-based C# mediator that uses source generators and C# interceptors to get as close to direct method call performance as possible.

### 🎯 What Makes It Different

- **🚀 Fast**: Only slight overhead compared to calling methods directly
- **⚡ Zero Boilerplate**: No interfaces, no base classes - just name your stuff `*Handler` and you're done
- **🔧 DI Just Works**: Full Microsoft.Extensions.DependencyInjection support out of the box
- **🎪 Rich Middleware**: Before/After/Finally hooks that can short-circuit or pass state around
- **🔄 Cascading Magic**: Return tuples and extra values get auto-published as new messages
- **🔒 Compile-Time Safety**: Source generator catches problems at build time, not runtime
- **📦 Multi-Project Ready**: Works great with vertical slice architecture

### 🧩 Dead Simple Example

```csharp
public record Ping(string Text);

public static class PingHandler
{
    public static string Handle(Ping msg) => $"Pong: {msg.Text}";
}

// That's it! No interfaces, no registration drama
var reply = mediator.Invoke<string>(new Ping("Hello"));
```

Would love to get some eyes on this from folks who've been thinking about mediator patterns. What do you think - does this approach resonate with anyone?

**Check it out:**
- 📦 [NuGet Package](https://www.nuget.org/packages/Foundatio.Mediator/)
- 🐙 [GitHub Repository](https://github.com/FoundatioFx/Foundatio.Mediator)
- 📖 [Docs & Examples](https://github.com/FoundatioFx/Foundatio.Mediator#readme)

**Comment by martinothamar** [comment]
Hi! Coincidentally I was just spending my morning catching up on issues and replies and preparing the release. I haven't replied for a month or so due to dayjob and vacation. Anyhow, here it is: https://www.nuget.org/packages/Mediator.Abstractions/3.0.1

As discussed previously this work has taken longer than I wanted to I decided to move the remaining issues to a v4 release. The work that has gone into v3 is still a lot and something I'm very happy with.

@ejsmith [Foundatio.Mediator](https://github.com/FoundatioFx/Foundatio.Mediator) looks great! Though a little off topic for this issue 😄 I really like the direction youre taking (conventions, interceptors, `Result<>`) and I think it's great to have an alternative that departs from the MediatR API in favor of offering more/different improvements. Maybe we should have an "Alternatives" section in the README? I'd happily take a PR for that

**Comment by goremykin** [comment]
@martinothamar, This is good news, thanks for your work!
Are there any changes since the last preview that we should know about?

**Comment by martinothamar** [comment]
Only this in the very latest prerelease: https://github.com/martinothamar/Mediator/issues/215

Later tonight I'll create a Github release with the changelog so it's easier to see what has gone into it since v2.1

**Comment by martinothamar** [comment]
Tag/release with changelog: https://github.com/martinothamar/Mediator/releases/tag/v3.0

**Comment by ejsmith** [comment]
> [@ejsmith](https://github.com/ejsmith) [Foundatio.Mediator](https://github.com/FoundatioFx/Foundatio.Mediator) looks great! Though a little off topic for this issue 😄 I really like the direction youre taking (conventions, interceptors, `Result<>`) and I think it's great to have an alternative that departs from the MediatR API in favor of offering more/different improvements. Maybe we should have an "Alternatives" section in the README? I'd happily take a PR for that

I've added a [Related Projects](https://github.com/FoundatioFx/Foundatio.Mediator?tab=readme-ov-file#-related-projects) to the readme in Foundatio Mediator. Would love if you would add an alternatives section like you mentioned. :-)
